spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: <yourusername>
    password: <yourpassword>

logging:
  level:
    com.laioffer.flagcamp.backend: DEBUG
    org.springframework.jdbc.core: DEBUG

  server:
    port: 8080
