spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: 19991118

logging:
  level:
    com.laioffer.flagcamp.backend: DEBUG
    org.springframework.jdbc.core: TRACE        
    org.springframework.data.jdbc: TRACE        
    org.springframework.jdbc.support: TRACE

  server:
    port: 8080
